### ISSUE TITLE
ERROR:  While executing gem ... Unknown command hyperledger_cli

### ISSUE THREAD

**Issue by mastercyb** [hyperledger/hyperledger-cli#1]
![screen shot 2015-02-17 at 02 24 29](https://cloud.githubusercontent.com/assets/410789/6222473/2ff1402e-b64c-11e4-87a8-34a8c4491379.png)

Could somebody help?

**Comment by DanielFeichtinger** [comment]
I think you might be missing `install` — it's `gem install hyperledger_cli`. If you have installed already it's just `hyperledger` to run the tool. Let me know if that works!
