### ISSUE TITLE
I am not able to install hyperledger_cli

### ISSUE THREAD

**Issue by sumghosh80** [hyperledger/hyperledger-cli#4]
Hi,

I am not able to install hyperledger_cli by writing command:-

> gem install hyperledger_cli 

It is giving me below error:-

ERROR:  Could not find a valid gem 'hyperledger_cli' (>= 0), here is why:
   Unable to download data from https://rubygems.org/ - Errno::ETIMEDOUT:
 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to 
respond. - connect(2) for "api.rubygems.org" port 443 (https://api.rubygems.org/latest_specs.4.8.gz)

I also tried through rubygems.org website, but no luck. Please help.

Thanks,
Sumit Ghosh

**Comment by danoprey** [comment]
This version has been retired:
http://digitalasset.com/posts/2015-11-09-hyperledger-beta-retired.html
